THETA_LAT_CUTOFF = 70.0

# 2D Map
N_BINS_PHI_NADIR = 180
PHI_NADIR_MIN, PHI_NADIR_MAX = 0.0, 360.0
D_PHI = (PHI_NADIR_MAX - PHI_NADIR_MIN)/N_BINS_PHI_NADIR

N_BINS_THETA_NADIR = 800
THETA_NADIR_MIN, THETA_NADIR_MAX = 0.0, 80.0
D_THETA = (THETA_NADIR_MAX - THETA_NADIR_MIN)/N_BINS_THETA_NADIR