import platform, os

EVENT_CLASS_NAMES = (
    'P8R2_SOURCE_V6',
    'P8R2_ULTRACLEANVETO_V6',
)
EVENT_CLASS_BITS = {
    'P8R2_SOURCE_V6': 7,
    'P8R2_ULTRACLEANVETO_V6': 10,
}

THETA_LAT_CUTOFF = 70.0
THETA_NADIR_CUT_MIN, THETA_NADIR_CUT_MAX = 68.4, 70.0
EVENT_CLASS = 24 # 24 = ULTRACLEANVETO
EV_CLASS = 1 # 0: "P8R2_SOURCE_V6", 1:"P8R2_ULTRACLEANVETO_V6"

IRF_NAME = EVENT_CLASS_NAMES[EV_CLASS]
EVENT_CLASS_BIT = EVENT_CLASS_BITS[IRF_NAME]

WEEK_BEGIN = 10
WEEK_END = 540

GAMMA = 2.66

# SPECTRUM
IS_ENERGY_BIAS = True
E_START_GEV = 10
E_STOP_GEV = 1000
N_E_BINS = 50

# Data directory
PATH_RAW_DATA = '/work/bus/Data'
PATH_EXTRACTED_DATA = '/work/jab/data/extracted'
if platform.system() == "Darwin":
    PATH_EXTRACTED_DATA = os.path.join(os.getcwd(), "data")

# 2D Map
N_BINS_PHI_NADIR = 180 # int(180/9)
PHI_NADIR_MIN, PHI_NADIR_MAX = 0.0, 360.0
D_PHI = (PHI_NADIR_MAX - PHI_NADIR_MIN)/N_BINS_PHI_NADIR

N_BINS_THETA_NADIR = 800 # int(800/8)
THETA_NADIR_MIN, THETA_NADIR_MAX = 0.0, 80.0
D_THETA = (THETA_NADIR_MAX - THETA_NADIR_MIN)/N_BINS_THETA_NADIR

### MPI
TAG_DONE = 0
TAG_INPROGRESS = 1